name: rfm_lakehouse
version: 1.0.0
config-version: 2
profile: rfm_lakehouse

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  rfm_lakehouse:
    silver:
      +materialized: table
      +schema: silver
      wcl_reports:
        +tags: [warcraftlogs, silver]
      wcl_fights:
        +tags: [warcraftlogs, silver]
      wcl_player_fight_metrics:
        +tags: [warcraftlogs, silver]
      wcl_ingestion_state:
        +tags: [warcraftlogs, silver]
    gold:
      +materialized: table
      +schema: gold
      wcl_boss_dps:
        +tags: [warcraftlogs, gold]
